### PR TITLE
Add project description and sketch to README

### PR DESCRIPTION
**Pull request by tonikarppi**

### CODE REVIEW

**Comment by macaullyjames** [comment]
Is @carllei alive? 😮

**Comment by tonikarppi** [comment]
We're researching the game APIs, so we're not posting any code yet. The things I put up are things we have discussed.

**Comment by macaullyjames** [comment]
It'd be great if you could move that discussion here (the issue tracker, not this PR specifically) 😉

**Comment by macaullyjames** [comment]
Either way, if you're working together you can use a tool like [git-pair](https://github.com/chrisk/git-pair) to give both of you credit in the commits, which is nice:

screen shot 2016-05-03 at 20 35 09

**Pull request merged**
